DROP TABLE IF EXISTS cpu;

CREATE TABLE cpu (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL, 
    content TEXT NOT NULL
);

DROP TABLE IF EXISTS gpu;

CREATE TABLE gpu (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL, 
    content TEXT NOT NULL
);

DROP TABLE IF EXISTS ram;

CREATE TABLE ram (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL, 
    content TEXT NOT NULL
);

DROP TABLE IF EXISTS ps;

CREATE TABLE ps (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL, 
    content TEXT NOT NULL
);