DROP TABLE IF EXISTS cpu;

CREATE TABLE cpu (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL, 
    content TEXT NOT NULL
);
